### ISSUE TITLE
Take advantage of the Regular Expressions Cache

### ISSUE THREAD

**Issue by DarkCow** [mizisu/DotGrok#2]
https://docs.microsoft.com/en-us/dotnet/standard/base-types/compilation-and-reuse-in-regular-expressions#the-regular-expressions-cache

https://github.com/mizisu/DotGrok/blob/e6d0a5855acbc9b5d7050f0cb1ac639805e47762/DotGrok/Grok.cs#L14

Could be refactored as

```cs
private static readonly Regex GrokPatternRegex = new Regex( @"%{(\w+):(\w+)}" );
//...
GrokPatternRegex.Replace( ... )
```

**Comment by mizisu** [comment]
Thank you for your effort!
I changed code for reuse regular expression
