### ISSUE TITLE
Suggestion: take advantage of 'internal' access modifier

### ISSUE THREAD

**Issue by amir734jj** [mizisu/DotGrok#3]
Make classes that don't need to be exposed outside of the NuGet package `internal`

**Comment by mizisu** [comment]
@amir734jj Thank you for your suggestion but could you tell me suggestion which one is need take advantage of 'internal' access modifier?

i want say more nicely but english is not my first language, sorry :)

Thanks

**Comment by mizisu** [comment]
If you need more discussion please reopen issue :)
